site_name: Generating Useful Synthetic Data
site_description: A library for generating and evaluating synthetic data for the NHS
repo_url: https://github.com/nhsx/NHSSynth
repo_name: nhsx/NHSSynth
edit_uri: edit/main/docs/

nav:
    - Home: index.md
    - User Guide:
        - Modules: modules.md
        - Development Guide: development_guide.md
        - Model Card: model_card.md
        - Secure Mode: secure_mode.md
    - Code Reference: reference/

theme:
  logo: assets/NHS.svg
  favicon: assets/NHS.svg
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate 
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.view
    - content.action.edit
    - content.code.copy
  icon:
    edit: material/pencil 
    view: material/eye

extra_css:
  - css/style.css
  - css/mkdocstrings.css

plugins:
  - search
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  generator: false