site_name: Generating Useful Synthetic Data
theme:
  logo: assets/NHS.svg
  favicon: assets/NHS.svg
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate 
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
    - content.action.view
    - content.action.edit
  icon:
    edit: material/pencil 
    view: material/eye

repo_url: https://github.com/nhsx/NHSSynth
repo_name: nhsx/NHSSynth
edit_uri: edit/main/docs/

nav:
    - Home: index.md
    - Model Card: model_card.md
    - Code Reference: reference/

plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     fallback_to_build_date: true
  # THIS DOESNT SEEM TO WORK

extra:
  generator: false