[tox]
envlist = py310
isolated_build = true

[testenv]
allowlist_externals = poetry
deps = setuptools
commands_pre =
    poetry install --with dev --no-root --sync
commands =
    poetry run pytest --import-mode importlib
