seed: 1
experiment_name: test
dataset: MIMIC_small
evaluation:
  column_shape_metrics:
  - KSComplement
  - TVComplement
  column_similarity_metrics:
  - CorrelationSimilarity
  - ContingencySimilarity
  detection_metrics:
  - SVCDetection
  boundary_metrics:
  - BoundaryAdherence
  coverage_metrics:
  - RangeCoverage
  - CategoryCoverage
  synthesis_metrics:
  - NewRowSynthesis