seed: 1
experiment_name: test
run_type: pipeline
dataloader:
  collapse_yaml: true
  write_csv: true
model:
  architecture:
    - VAE
    - DPVAE
  num_epochs: 30
  target_epsilon:
    - 1.0
    - 3.0
    - 6.0
  max_grad_norm: 5.0
  secure_mode: false
  repeats: 3
evaluation:
  downstream_tasks: true
  column_shape_metrics:
  - KSComplement
  - TVComplement
  column_similarity_metrics:
  - CorrelationSimilarity
  - ContingencySimilarity
  boundary_metrics:
  - BoundaryAdherence
  coverage_metrics:
  - RangeCoverage
  - CategoryCoverage
  synthesis_metrics:
  - NewRowSynthesis
  divergence_metrics:
  - ContinuousKLDivergence
  - DiscreteKLDivergence