seed: 1
experiment_name: test
run_type: pipeline
dataset: MIMIC_small
dataloader:
  data_dir: data/.nosync
  sdv_workflow: false
  collapse_yaml: true
model:
  num_epochs: 20
  # target_epsilon: 1.0
  # secure_rng: true
  non_private_training: true
evaluation:
  column_shape_metrics:
  - KSComplement
  - TVComplement
  column_similarity_metrics:
  - CorrelationSimilarity
  - ContingencySimilarity
  detection_metrics:
  - SVCDetection
  boundary_metrics:
  - BoundaryAdherence
  coverage_metrics:
  - RangeCoverage
  - CategoryCoverage
  synthesis_metrics:
  - NewRowSynthesis
plotting:
  plot-tsne: true
  plot-sdv-report: true