seed: 1
experiment_name: test
run_type: pipeline
dataset: MIMIC_small
dataloader:
  data_dir: data/.nosync
  sdv_workflow: false
  collapse_yaml: true
model:
  num_epochs: 50
  target_epsilon: 1.0
  secure_rng: true
evaluation:
  diagnostic: true
  quality: true