seed: 1
experiment_name: test
dataset: MIMIC_small
dataloader:
  sdv_workflow: false
  collapse_yaml: true
model:
  num_epochs: 500
  non_private_training: true
evaluation:
  column_shape_metrics:
  - KSComplement
  - TVComplement
  column_similarity_metrics:
  - CorrelationSimilarity
  - ContingencySimilarity
  detection_metrics:
  - SVCDetection
  boundary_metrics:
  - BoundaryAdherence
  coverage_metrics:
  - RangeCoverage
  - CategoryCoverage
  synthesis_metrics:
  - NewRowSynthesis
plotting:
  plot_tsne: true
  plot_sdv_report: true