seed: 1
experiment_name: test
dataloader:
  allow_null_transformers: false
  collapse_yaml: false
model:
  architecture:
    - VAE
    - DPVAE
  num_epochs: 20
  target_epsilon: 1.0
  max_grad_norm: 5.0
  secure_mode: false
evaluation:
  column_shape_metrics:
  - KSComplement
  - TVComplement
  column_similarity_metrics:
  - CorrelationSimilarity
  - ContingencySimilarity
  detection_metrics:
  - SVCDetection
  boundary_metrics:
  - BoundaryAdherence
  coverage_metrics:
  - RangeCoverage
  - CategoryCoverage
  synthesis_metrics:
  - NewRowSynthesis
  divergence_metrics:
  - ContinuousKLDivergence
  - DiscreteKLDivergence
plotting:
  plot_tsne: true
  plot_sdv_report: true