name: Run `black` and `ruff` to ensure correct formatting and that there are no linting errors in the code

on: [push, pull_request]

jobs:
  check_format:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Run black
      uses: psf/black@stable
      with:
        jupyter: true
    - name: Run ruff
      uses: chartboost/ruff-action@v1
